### ISSUE TITLE
Game Keeps Crashing

### ISSUE THREAD

**Issue by Mohamedd-Ashraf** [spacecollapse/Rust#3]
the game keeps crashing -unity exception- after injecting with the new cheat update -2555- once I join the server

**Comment by spacecollapse** [comment]
don't turn on aim in cheat

**Comment by Mohamedd-Ashraf** [comment]
> don't turn on aim in cheat

I did not turn on any aim-related features in the cheat. I only opened the EAC bypass and launched Rust. After joining the server, I injected Superiority, but the game crashed instantly. I didn't activate any features in the cheat. If I don't inject it, the game doesn't crash.

**Comment by spacecollapse** [comment]
rust - alkad? try install this https://github.com/spacecollapse/flight/releases/download/komponents/archive.zip
and reload pc

**Comment by Mohamedd-Ashraf** [comment]
Yes, Alkad Rust. I just realized it crashes only when I inject on this server 'Connect 2.arabrust.net:28035.' I don't know why, but it was working fine, and I was using Superiority on that server on the last update '2553.

**Comment by spacecollapse** [comment]
i think need wait when superiority update full, and all problems was fixed

**Comment by spacecollapse** [comment]
cheat update, need to test for crashes, also added eacbypass with english interface

**Comment by Mohamedd-Ashraf** [comment]
still crashing

**Comment by Mohamedd-Ashraf** [comment]
not crashing anymore after disabling "Use consoleRun Hook"
